### ISSUE TITLE
cant find link to blog

### ISSUE THREAD

**Issue by alphaolomi** [nab-in/bookish-broccoli#38]
the About says  "A blog by readers for readers" where can I find the link to the live blog.

**Comment by BaharaJr** [comment]
Hello, @alphaolomi this is one of those dead side projects 😅 but hey I and @rafiiramii will soon comeback to it.

**Comment by alphaolomi** [comment]
Sad looks like a nice project, a comeback will be nice. :smile:

**Comment by BaharaJr** [comment]
Yeah, we will definitely come back when time allows.
